channels:
  - conda-forge
dependencies:
  - python = 3
  - bokeh = 1.1.0
  - dask = 2.0.0
  - dask-image = 0.2.0
  - dask-ml = 1.0.0
  - nodejs = 8.9
  - notebook < 5.7.5
  - tornado = 5
  - numba
  - numpy
  - pip
  - pandas
  - pyarrow == 0.12.1
  - fastparquet
  - python-graphviz
  - seaborn
  - scikit-learn = 0.20
  - matplotlib
  - nbserverproxy
  - nomkl
  - h5py
  - xarray
  - bottleneck
  - requests
  - py-xgboost
  - boto3
  - botocore
  - s3fs
  - s3transfer
  - pip:
    - dask_xgboost
    - mimesis
    - jupyterlab == 1.0.0rc0
    - dask-labextension == 0.4.0a1
